[build]
  publish = "web"
  command = "echo no-build"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/openai/chat"
  to = "/.netlify/functions/openai-chat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
